[phases.setup]
nixPkgs = ["ffmpeg"]
aptPkgs = ["wget", "python3", "python3-pip"]
cmds = [
    "curl -fsSL https://deb.nodesource.com/setup_18.x | bash -",
    "apt-get install -y nodejs"
]

[phases.install]
cmds = [
    "cd frontend && npm ci",
    "cd backend && pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && NODE_ENV=production npm run build"
]

[start]
cmd = "cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
NODE_ENV = "production"
