# Specify the providers (NodeJS for frontend, Python for backend)
providers = ["nodejs", "python"]

[phases.setup]
nixPkgs = ["ffmpeg"]
aptPkgs = ["wget"]

[phases.install]
cmds = [
    "cd frontend && npm install",
    "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
NODE_ENV = "production"
